/**
 * Renders every template to HTML once, at build time.
 *
 * @react-email/render cannot run in the Workers runtime — it peers on real
 * react-dom/server and pulls Node-only dependencies (resend/resend-node#587 is
 * this exact bundling failure). So the React lives here, the Worker ships
 * strings, and `{{placeholders}}` carry the only per-send data.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pixelBasedPreset, Tailwind } from '@react-email/components';
import { render } from '@react-email/render';
import SignIn from '../src/templates/sign-in';
import * as signInMeta from '../src/templates/sign-in.meta';

const here = dirname(fileURLToPath(import.meta.url));
const APP_STYLESHEET = resolve(here, '../../../apps/worker/web/style.css');

/**
 * The app's `@theme` colours, as the JS config `<Tailwind>` actually accepts.
 *
 * `@react-email/tailwind@2` takes `config?: Omit<Config, 'content'>` and has no
 * CSS-first `theme` prop — passing one is silently ignored, which renders every
 * branded class as unstyled default. So the v4 token block is parsed here into
 * the v3-shaped config instead, which keeps `style.css` the single source
 * without pretending an API exists that does not.
 */
async function appColors(): Promise<Record<string, string>> {
  const css = await readFile(APP_STYLESHEET, 'utf8');
  const start = css.indexOf('@theme');
  if (start === -1) throw new Error(`no @theme block in ${APP_STYLESHEET} — emails would fall back to stock Tailwind`);
  let depth = 0;
  let end = -1;
  for (let i = css.indexOf('{', start); i < css.length; i++) {
    if (css[i] === '{') depth++;
    else if (css[i] === '}' && --depth === 0) {
      end = i;
      break;
    }
  }
  if (end === -1) throw new Error(`unbalanced @theme block in ${APP_STYLESHEET}`);

  const colors: Record<string, string> = {};
  const skipped: string[] = [];
  for (const [, name, value] of css.slice(start, end).matchAll(/--color-ml-([\w-]+):\s*([^;]+);/g)) {
    const trimmed = value.trim();
    // Email clients do not understand oklch() or colour-mix(). Dropping them
    // loudly beats shipping a colour half the inboxes render as black.
    if (/^#|^rgb|^hsl/.test(trimmed)) colors[`ml-${name}`] = trimmed;
    else skipped.push(`ml-${name}: ${trimmed}`);
  }
  if (skipped.length > 0) {
    console.warn(
      `build-emails — skipped ${skipped.length} token(s) email clients cannot render:\n  ${skipped.join('\n  ')}`,
    );
  }
  return colors;
}

const templates = [{ meta: signInMeta, component: SignIn, constant: 'SIGN_IN_HTML' }];

const colors = await appColors();

const parts: string[] = [
  '// GENERATED by `bun run build` in packages/emails. Do not edit.',
  '// Source: src/templates/*.tsx, themed from apps/worker/web/style.css.',
  '',
];

for (const { meta, component, constant } of templates) {
  const Template = component;
  // Tailwind wraps here rather than inside Layout, so templates stay free of
  // build concerns and the theme has exactly one injection point.
  const html = await render(
    <Tailwind config={{ presets: [pixelBasedPreset], theme: { extend: { colors } } }}>
      <Template />
    </Tailwind>,
  );
  if (!html.includes(meta.PLACEHOLDER.link)) {
    throw new Error(`${meta.id}: the {{link}} placeholder did not survive rendering — every send would be a dead link`);
  }
  // A surviving class attribute means Tailwind could not resolve that utility,
  // so the element shipped unstyled. This is the exact failure a silently
  // ignored config produces, and it is invisible in a rendered preview.
  const unresolved = [...html.matchAll(/class="([^"]+)"/g)].map((match) => match[1]);
  if (unresolved.length > 0) {
    throw new Error(`${meta.id}: Tailwind left ${unresolved.length} class(es) unresolved: ${unresolved.join(', ')}`);
  }
  // rem is unreliable in Outlook; pixelBasedPreset converts scale utilities but
  // not arbitrary values, so those have to be authored in px.
  const rem = [...html.matchAll(/[\d.]+rem/g)].map((match) => match[0]);
  if (rem.length > 0) {
    throw new Error(`${meta.id}: rem units survived (${[...new Set(rem)].join(', ')}) — use px in arbitrary values`);
  }
  parts.push(`export const ${constant} = ${JSON.stringify(html)};`);
}

await writeFile(resolve(here, '../src/generated.ts'), `${parts.join('\n')}\n`);
console.log(`build-emails — rendered ${templates.length} template(s)`);
