#!/usr/bin/env python3
"""Bake the OG card's Geist faces into apps/worker/src/og-fonts.ts.

Run by hand when apps/site/public/fonts/geist-latin.woff2 changes:

    python3 apps/worker/scripts/build-og-fonts.py

The card used to pull its font from the Google Fonts CSS API at render time,
matching a `.ttf` URL out of the response. Google switched that response to
`.woff` for the User-Agent it was sending, the regex stopped matching, and every
OG request threw — a third-party format change silently broke the endpoint. The
faces are part of the worker now.

Static instances, not the variable font: resvg does not apply variation axes, so
a variable file renders every weight at its default and the card loses its
hierarchy. Base64 rather than a bundler asset import, because that needs no
plugin config and is the same in dev, test and deploy.

Geist is licensed OFL 1.1 (github.com/vercel/geist-font), which permits bundling.

Requires: pip install fonttools brotli
"""

import base64
import pathlib
import io
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.subset import Subsetter

ROOT = pathlib.Path(__file__).resolve().parents[3]
SRC = ROOT / "apps/site/public/fonts/geist-latin.woff2"
OUT = ROOT / "apps/worker/src/og-fonts.ts"

# Latin-1 covers every hostname (IDNs reach the card already punycoded) plus the
# card's own copy; the three extras are the stat line's separator, the truncation
# ellipsis, and the non-breaking spaces holding that line apart.
UNICODES = list(range(0x20, 0x7F)) + list(range(0xA0, 0x100)) + [0x2026, 0x2018, 0x2019, 0x201C, 0x201D]

WEIGHTS = {"regular": 400, "medium": 500, "bold": 700}


def instance(weight: int) -> bytes:
    font = TTFont(SRC)
    instantiateVariableFont(font, {"wght": weight}, inplace=True, updateFontNames=False)
    subsetter = Subsetter()
    subsetter.populate(unicodes=UNICODES)
    subsetter.subset(font)
    font.flavor = None
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


faces = {name: instance(w) for name, w in WEIGHTS.items()}
lines = [
    "// GENERATED by apps/worker/scripts/build-og-fonts.py — do not edit.",
    "// Geist (OFL 1.1, github.com/vercel/geist-font), subset to latin + the",
    "// card's punctuation and flattened to three static weights for resvg.",
    "",
    "/** Base64 TTFs, decoded once per isolate in og.ts. */",
    "export const OG_FONTS_BASE64 = [",
]
for name, data in faces.items():
    lines.append(f"  // Geist {name} ({len(data) // 1024}KB)")
    lines.append(f"  '{base64.b64encode(data).decode()}',")
lines.append("];")
OUT.write_text("\n".join(lines) + "\n")

total = sum(len(d) for d in faces.values())
print(f"wrote {OUT.relative_to(ROOT)} — {total // 1024}KB of TTF, {OUT.stat().st_size // 1024}KB on disk")
