#!/usr/bin/env python3
"""Bake the OG card's Geist faces into apps/worker/src/og-fonts.ts.

Run by hand when apps/site/public/fonts/geist-latin.woff2 changes:

    python3 apps/worker/scripts/build-og-fonts.py

The card used to pull its font from the Google Fonts CSS API at render time,
matching a `.ttf` URL out of the response. Google switched that response to
`.woff` for the User-Agent it was sending, the regex stopped matching, and every
OG request threw — a third-party format change silently broke the endpoint. The
faces are part of the worker now.

Static instances, not the variable font: resvg does not apply variation axes, so
a variable file renders every weight at its default and the card loses its
hierarchy. Base64 rather than a bundler asset import, because that needs no
plugin config and is the same in dev, test and deploy.

Geist is licensed OFL 1.1 (github.com/vercel/geist-font), which permits bundling.

Requires: pip install fonttools brotli
"""

import base64
import pathlib
import io
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.subset import Subsetter

ROOT = pathlib.Path(__file__).resolve().parents[3]
SRC = ROOT / "apps/site/public/fonts/geist-latin.woff2"
OUT = ROOT / "apps/worker/src/og-fonts.ts"

# Latin-1 covers every hostname (IDNs reach the card already punycoded) plus the
# card's own copy; the three extras are the stat line's separator, the truncation
# ellipsis, and the non-breaking spaces holding that line apart.
UNICODES = list(range(0x20, 0x7F)) + list(range(0xA0, 0x100)) + [0x2026, 0x2018, 0x2019, 0x201C, 0x201D]

WEIGHTS = {"regular": 400, "medium": 500, "bold": 700}

# The heading on the page card wraps and gets a stroke drawn under one of its
# words, so both need to know how wide a string actually is. Guessed advances put
# that stroke under the wrong word, so they are measured off the same face that
# renders.
ADVANCE_FACE = "bold"


def instance(weight: int) -> tuple[bytes, TTFont]:
    font = TTFont(SRC)
    instantiateVariableFont(font, {"wght": weight}, inplace=True, updateFontNames=False)
    subsetter = Subsetter()
    subsetter.populate(unicodes=UNICODES)
    subsetter.subset(font)
    font.flavor = None
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue(), font


def advances(font: TTFont) -> dict[str, int]:
    """Per-mille-of-em advance for every subset codepoint, keyed by character."""
    em = font["head"].unitsPerEm
    widths = font["hmtx"].metrics
    reverse = font.getBestCmap()
    out: dict[str, int] = {}
    for code in UNICODES:
        name = reverse.get(code)
        if name is None or name not in widths:
            continue
        out[chr(code)] = round(widths[name][0] * 1000 / em)
    return out


built = {name: instance(w) for name, w in WEIGHTS.items()}
faces = {name: data for name, (data, _) in built.items()}
advance_table = advances(built[ADVANCE_FACE][1])
lines = [
    "// GENERATED by apps/worker/scripts/build-og-fonts.py — do not edit.",
    "// Geist (OFL 1.1, github.com/vercel/geist-font), subset to latin + the",
    "// card's punctuation and flattened to three static weights for resvg.",
    "",
    "/** Base64 TTFs, decoded once per isolate in og.ts. */",
    "export const OG_FONTS_BASE64 = [",
]
for name, data in faces.items():
    lines.append(f"  // Geist {name} ({len(data) // 1024}KB)")
    lines.append(f"  '{base64.b64encode(data).decode()}',")
lines.append("];")
lines.append("")
lines.append("/**")
lines.append(f" * Advance widths of Geist {ADVANCE_FACE}, packed as a character followed by four")
lines.append(" * digits of thousandths-of-an-em, unpacked once in og-page-card.ts.")
lines.append(" *")
lines.append(" * The page card measures its heading with these: it wraps the text itself and")
lines.append(" * draws a stroke under one word, and neither survives a guessed width. Packed")
lines.append(" * rather than written out as an object because 195 quoted single-character keys")
lines.append(" * is 195 lines of generated source saying nothing.")
lines.append(" */")
packed = "".join(f"{ch}{advance_table[ch]:04d}" for ch in sorted(advance_table))
escaped = packed.replace("\\", "\\\\").replace("'", "\\'")
# Split across two lines: Biome's formatter breaks after `=` at this width.
lines.append("export const OG_HEADING_ADVANCES_PACKED =")
lines.append(f"  '{escaped}';")
OUT.write_text("\n".join(lines) + "\n")
